services:
  # app:
  #   build:
  #     context: .
  #     image: approve-me-api
  #   depends_on:
  #     - db
  #   networks:
  #     - approve-me-network
  #   ports:
  #     - 8080:8080
  #     - 8081:8081
  #   restart: unless-stopped

  db:
    image: postgres:17.2
    container_name: approveme-db
    env_file:
      - ./approve-me-db/.env
    volumes:
      - ./approve-me-db/pgdata:/var/lib/mysql
    networks:
      - approve-me-network
    ports:
      - 11279:5432
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: approveme-redis
    ports:
      - "16379:6379"
    volumes:
      - ./approve-me-redis/data:/data
    command: ["redis-server", "--appendonly", "yes"]
    env_file:
      - ./approve-me-redis/.env
    restart: unless-stopped

networks:
  approve-me-network:
